2023-07-12 10:33:03,828 INFO    MainThread:6276 [wandb_setup.py:_flush():76] Current SDK version is 0.15.2
2023-07-12 10:33:03,829 INFO    MainThread:6276 [wandb_setup.py:_flush():76] Configure stats pid to 6276
2023-07-12 10:33:03,829 INFO    MainThread:6276 [wandb_setup.py:_flush():76] Loading settings from C:\Users\LZW\.config\wandb\settings
2023-07-12 10:33:03,829 INFO    MainThread:6276 [wandb_setup.py:_flush():76] Loading settings from E:\rk3399pro开发板资料\yolov5-code-main\wandb\settings
2023-07-12 10:33:03,848 INFO    MainThread:6276 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-12 10:33:03,848 INFO    MainThread:6276 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'E:\\rk3399pro开发板资料\\yolov5-code-main\\train.py'}
2023-07-12 10:33:03,849 INFO    MainThread:6276 [wandb_setup.py:_flush():76] Applying login settings: {'login_timeout': 30}
2023-07-12 10:33:03,849 INFO    MainThread:6276 [wandb_init.py:_log_setup():507] Logging user logs to E:\rk3399pro开发板资料\yolov5-code-main\wandb\run-20230712_103303-ctbwr956\logs\debug.log
2023-07-12 10:33:03,849 INFO    MainThread:6276 [wandb_init.py:_log_setup():508] Logging internal logs to E:\rk3399pro开发板资料\yolov5-code-main\wandb\run-20230712_103303-ctbwr956\logs\debug-internal.log
2023-07-12 10:33:03,849 INFO    MainThread:6276 [wandb_init.py:init():547] calling init triggers
2023-07-12 10:33:03,849 INFO    MainThread:6276 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'weights': 'yolov5s.pt', 'cfg': 'models\\yolov5s-mobilenet.yaml', 'data': 'data\\bvn.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}, 'epochs': 100, 'batch_size': 16, 'imgsz': 640, 'rect': False, 'resume': False, 'nosave': False, 'noval': False, 'noautoanchor': False, 'noplots': False, 'evolve': None, 'bucket': '', 'cache': None, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'optimizer': 'SGD', 'sync_bn': False, 'workers': 8, 'project': 'runs\\train', 'name': 'exp', 'exist_ok': False, 'quad': False, 'cos_lr': False, 'label_smoothing': 0.0, 'patience': 100, 'freeze': [0], 'save_period': -1, 'seed': 0, 'local_rank': -1, 'entity': None, 'upload_dataset': False, 'bbox_interval': -1, 'artifact_alias': 'latest', 'save_dir': 'runs\\train\\exp'}
2023-07-12 10:33:03,850 INFO    MainThread:6276 [wandb_init.py:init():596] starting backend
2023-07-12 10:33:03,850 INFO    MainThread:6276 [wandb_init.py:init():600] setting up manager
2023-07-12 10:33:03,853 INFO    MainThread:6276 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-07-12 10:33:03,901 INFO    MainThread:6276 [wandb_init.py:init():606] backend started and connected
2023-07-12 10:33:03,903 INFO    MainThread:6276 [wandb_init.py:init():700] updated telemetry
2023-07-12 10:33:03,905 INFO    MainThread:6276 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-07-12 10:34:04,466 ERROR   MainThread:6276 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-12 10:34:04,600 ERROR   MainThread:6276 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "D:\LZW\Anaconda3\envs\yolov5-v2\lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
  File "D:\LZW\Anaconda3\envs\yolov5-v2\lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-12 10:34:05,608 WARNING MsgRouterThr:6276 [router.py:message_loop():77] message_loop has been closed
